version: '3.6'

volumes:
  particl_data:
  particlcore:

services:
  partyman:
    image: hub.hel.lan/partyman:2024-09-11_1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINER_TIMEZONE="Europe/UTC"
    command: bin/entrypoint.sh
    ports:
      - "40801:8080"
      - "51738:51738"
    volumes:
      - particlcore:/root/particlcore
      - particl_data:/root/.particl
      - ./conf/particl.conf:/root/.particl/particl.conf
      # - ./conf/crontab:/root/partyman/crontab
      # - ./logs/debug.log:/root/.particl/debug.log
      # - ./logs/cron.log:/root/partyman/cron.log

      # - ../lib/functions.sh:/root/partyman/lib/functions.sh
      # - ../bin/partyman.sh:/root/partyman/bin/partyman.sh
    environment:
      - PARTICL_DIR=/root/particlcore
      - PARTICL_DATADIR=/root/.particl
      - PARTYMAN_DIR=/root/partyman
      - HTML_PATH=/root/partyman/webserver/public_html
      - DEBUG=0
      - PRINTTOCONSOLE=1
